# Generated by Django 4.1 on 2022-08-11 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressdetails',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='addressDetails', to='delapp.employee'),
        ),
    ]
