# Generated by Django 4.1 on 2022-08-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delapp', '0002_alter_addressdetails_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(upload_to='pic'),
        ),
    ]
